"""Calibration utility for APDS-9960 color sensors.

Run this script interactively on the Pi to calibrate RGB reference values
for each ligand color. For each color, place that ligand under ALL sensors,
then readings are taken from every sensor and averaged to color_map.json.

Usage:
    python color_calibration.py
"""

import json
import time
import sys

from sensor_service import SensorService
from config import LIGAND_COLORS, COLOR_MAP_PATH, NUM_SENSORS


def calibrate():
    print("=== APDS-9960 Color Calibration Utility ===\n")
    print("This utility will help you calibrate the color sensors.")
    print(f"For each color, place that ligand under ALL {NUM_SENSORS} sensors,")
    print("then readings will be taken from every sensor and averaged.\n")

    service = SensorService()
    service.initialize()

    calibrated = {}

    for color_name in LIGAND_COLORS:
        input(f"\nPlace the {color_name} ligand under ALL sensors and press Enter...")

        all_readings = []
        for ch in range(NUM_SENSORS):
            print(f"  Reading sensor {ch}...", end="", flush=True)
            for _ in range(10):
                raw = service.read_raw(ch)
                if raw is not None:
                    all_readings.append(raw)
                time.sleep(0.1)
            print(" done.")

        if not all_readings:
            print(f"  ERROR: No readings for {color_name}. Check sensor connections.")
            continue

        # Average across all sensors
        avg_r = sum(r for r, g, b, c in all_readings) / len(all_readings)
        avg_g = sum(g for r, g, b, c in all_readings) / len(all_readings)
        avg_b = sum(b for r, g, b, c in all_readings) / len(all_readings)
        avg_c = sum(c for r, g, b, c in all_readings) / len(all_readings)

        nr, ng, nb = service.normalize_rgb(avg_r, avg_g, avg_b)

        print(f"  Avg Raw RGBC: ({avg_r:.0f}, {avg_g:.0f}, {avg_b:.0f}, {avg_c:.0f})")
        print(f"  Normalized (0-1000): ({nr}, {ng}, {nb})")

        calibrated[color_name] = {"r": nr, "g": ng, "b": nb}

    # Calibrate "None" (empty slot) as its own color
    input("\nRemove all ligands (empty slots) and press Enter...")
    all_empty = []
    for ch in range(NUM_SENSORS):
        print(f"  Reading empty sensor {ch}...", end="", flush=True)
        for _ in range(10):
            raw = service.read_raw(ch)
            if raw is not None:
                all_empty.append(raw)
            time.sleep(0.1)
        print(" done.")

    if all_empty:
        avg_r = sum(r for r, g, b, c in all_empty) / len(all_empty)
        avg_g = sum(g for r, g, b, c in all_empty) / len(all_empty)
        avg_b = sum(b for r, g, b, c in all_empty) / len(all_empty)
        nr, ng, nb = service.normalize_rgb(avg_r, avg_g, avg_b)
        print(f"  Normalized (0-1000): ({nr}, {ng}, {nb})")
        calibrated["None"] = {"r": nr, "g": ng, "b": nb}

    # Save
    color_map = {
        "_comment": "Calibrated RGB reference values. Generated by color_calibration.py.",
        "colors": calibrated,
    }

    with open(COLOR_MAP_PATH, "w") as f:
        json.dump(color_map, f, indent=2)

    print(f"\nCalibration saved to {COLOR_MAP_PATH}")
    print("\nCalibrated values:")
    for name, rgb in calibrated.items():
        print(f"  {name}: R={rgb['r']}, G={rgb['g']}, B={rgb['b']}")


if __name__ == "__main__":
    calibrate()
