"""Calibration utility for APDS-9960 color sensors via Arduino serial.

Same interactive calibration workflow as color_calibration.py, but communicates
with the Arduino I/O board over USB serial instead of reading sensors directly.
Calibration data is stored in Arduino EEPROM and optionally saved to
color_map.json for reference.

Usage:
    python color_calibration_serial.py
    python color_calibration_serial.py --port /dev/ttyACM0
"""

import argparse
import json
import math

from serial_service import SerialService
from config import LIGAND_COLORS, COLOR_MAP_PATH, NUM_SENSORS, SERIAL_PORT


def normalize_by_clear(r, g, b, c):
    if c == 0:
        return (0, 0, 0)
    return (
        round(1000.0 * r / c),
        round(1000.0 * g / c),
        round(1000.0 * b / c)
    )


def calibrate():
    parser = argparse.ArgumentParser(description="Color calibration via Arduino")
    parser.add_argument("--port", default=SERIAL_PORT,
                        help=f"Arduino serial port (default: {SERIAL_PORT})")
    args = parser.parse_args()

    print("=== Color Calibration (Arduino Serial) ===\n")
    print(f"Connecting to Arduino on {args.port}...")

    service = SerialService(port=args.port)
    service.initialize()

    if service.ser is None:
        print("ERROR: Could not connect to Arduino.")
        return

    print(f"Connected. Calibrating {NUM_SENSORS} sensors.\n")
    print(f"For each color, place that ligand under ALL {NUM_SENSORS} sensors,")
    print("then readings will be taken and stored per-sensor.\n")

    # Per-sensor calibration data
    sensor_maps = {ch: {} for ch in range(NUM_SENSORS)}
    raw_clears = {ch: [] for ch in range(NUM_SENSORS)}

    for color_name in LIGAND_COLORS:
        input(f"\nPlace the {color_name} ligand under ALL sensors and press Enter...")

        for ch in range(NUM_SENSORS):
            print(f"  Reading sensor {ch}...", end="", flush=True)
            resp = service.calibrate_sample(ch)
            if resp is None or "error" in resp:
                print(" ERROR: no readings.")
                continue

            r, g, b, c = resp["r"], resp["g"], resp["b"], resp["c"]
            nr, ng, nb = normalize_by_clear(r, g, b, c)
            sensor_maps[ch][color_name] = {
                "r": nr, "g": ng, "b": nb, "raw_c": round(c)
            }
            raw_clears[ch].append(round(c))
            print(f" done. Raw RGBC: ({r}, {g}, {b}, {c})"
                  f"  R/C G/C B/C: ({nr}, {ng}, {nb})")

    # Calibrate "None" (empty slot)
    input("\nRemove all ligands (empty slots) and press Enter...")

    empty_proxs = {}
    for ch in range(NUM_SENSORS):
        print(f"  Reading empty sensor {ch}...", end="", flush=True)
        resp = service.calibrate_sample(ch)
        if resp is None or "error" in resp:
            print(" ERROR: no readings.")
            continue

        r, g, b, c, prox = resp["r"], resp["g"], resp["b"], resp["c"], resp["prox"]
        nr, ng, nb = normalize_by_clear(r, g, b, c)
        sensor_maps[ch]["None"] = {
            "r": nr, "g": ng, "b": nb, "raw_c": round(c)
        }
        raw_clears[ch].append(round(c))
        empty_proxs[ch] = prox
        print(f" done. R/C G/C B/C: ({nr}, {ng}, {nb})  Raw C: {c}  Prox: {prox}")

    # Compute max clear per sensor and scale clear to 0-1000
    clear_max = {}
    for ch in range(NUM_SENSORS):
        if raw_clears[ch]:
            clear_max[ch] = max(raw_clears[ch])
            for name in sensor_maps[ch]:
                raw_c = sensor_maps[ch][name]["raw_c"]
                sensor_maps[ch][name]["sc"] = round(1000.0 * raw_c / clear_max[ch])
                del sensor_maps[ch][name]["raw_c"]

    # Calibrate proximity thresholds
    input("\nPlace any ligand under ALL sensors and press Enter...")
    print("\n  Reading filled slot proximity values...")

    proximity_thresholds = {}
    for ch in range(NUM_SENSORS):
        print(f"  Reading sensor {ch}...", end="", flush=True)
        resp = service.calibrate_sample(ch)
        if resp and "prox" in resp and ch in empty_proxs:
            prox = resp["prox"]
            proximity_thresholds[ch] = round((empty_proxs[ch] + prox) / 2)
            print(f" done. Prox: {prox}"
                  f"  (empty={empty_proxs[ch]}, threshold={proximity_thresholds[ch]})")
        else:
            print(f" done. Prox: {resp.get('prox') if resp else '?'}")

    # Build calibration data
    color_map = {
        "_comment": "Per-sensor 4D color values. Generated by color_calibration_serial.py.",
        "sensors": {str(ch): colors for ch, colors in sensor_maps.items()},
        "clear_max": {str(ch): v for ch, v in clear_max.items()},
        "proximity_thresholds": {str(ch): t for ch, t in proximity_thresholds.items()},
    }

    # Save to Arduino EEPROM
    print("\nSaving calibration to Arduino EEPROM...", end="", flush=True)
    if service.calibrate_save(color_map):
        print(" done.")
    else:
        print(" FAILED.")

    # Also save local JSON copy for reference
    with open(COLOR_MAP_PATH, "w") as f:
        json.dump(color_map, f, indent=2)
    print(f"Local copy saved to {COLOR_MAP_PATH}")

    # Print summary
    print("\nCalibrated values per sensor:")
    for ch in range(NUM_SENSORS):
        print(f"\n  Sensor {ch} (clear_max={clear_max.get(ch, '?')}):")
        for name, vals in sensor_maps[ch].items():
            print(f"    {name}: R/C={vals['r']}, G/C={vals['g']}, "
                  f"B/C={vals['b']}, SC={vals['sc']}")

    service.cleanup()


if __name__ == "__main__":
    calibrate()
