"""Calibration utility for APDS-9960 color sensors.

Run this script interactively on the Pi to calibrate RGB reference values
for each ligand color. For each color, place that ligand under ALL sensors,
then readings are taken and stored per-sensor to color_map.json.

Empty slots ("None") are also calibrated as a color. Proximity is calibrated
as an additional hint for empty detection, but color matching handles the
case where some materials don't reflect IR well.

Usage:
    python color_calibration.py
"""

import json
import time
import sys

from sensor_service import SensorService
from config import LIGAND_COLORS, COLOR_MAP_PATH, NUM_SENSORS


def read_sensor_avg(service, channel, num_samples=10, delay=0.1):
    """Take multiple readings from a single sensor and return the average RGBC."""
    readings = []
    for _ in range(num_samples):
        raw = service.read_raw(channel)
        if raw is not None:
            readings.append(raw)
        time.sleep(delay)

    if not readings:
        return None

    avg_r = sum(r for r, g, b, c in readings) / len(readings)
    avg_g = sum(g for r, g, b, c in readings) / len(readings)
    avg_b = sum(b for r, g, b, c in readings) / len(readings)
    avg_c = sum(c for r, g, b, c in readings) / len(readings)
    return (avg_r, avg_g, avg_b, avg_c)


def read_proximity_avg(service, channel, num_samples=10, delay=0.1):
    """Take multiple proximity readings from a single sensor and return the average."""
    readings = []
    for _ in range(num_samples):
        prox = service.read_proximity(channel)
        if prox is not None:
            readings.append(prox)
        time.sleep(delay)

    if not readings:
        return None
    return sum(readings) / len(readings)


def calibrate():
    print("=== APDS-9960 Color Calibration Utility ===\n")
    print("This utility will help you calibrate the color sensors.")
    print(f"For each color, place that ligand under ALL {NUM_SENSORS} sensors,")
    print("then readings will be taken and stored per-sensor.\n")

    service = SensorService()
    service.initialize()

    # Per-sensor calibration: sensors[ch][color_name] = {r, g, b, nc}
    sensor_maps = {ch: {} for ch in range(NUM_SENSORS)}

    for color_name in LIGAND_COLORS:
        input(f"\nPlace the {color_name} ligand under ALL sensors and press Enter...")

        for ch in range(NUM_SENSORS):
            print(f"  Reading sensor {ch}...", end="", flush=True)
            avg = read_sensor_avg(service, ch)
            if avg is None:
                print(" ERROR: no readings.")
                continue

            avg_r, avg_g, avg_b, avg_c = avg
            nr, ng, nb = service.normalize_rgb(avg_r, avg_g, avg_b)
            nc = service.normalize_clear(avg_r, avg_g, avg_b, avg_c)
            sensor_maps[ch][color_name] = {"r": nr, "g": ng, "b": nb, "nc": nc}
            print(f" done. Raw RGBC: ({avg_r:.0f}, {avg_g:.0f}, {avg_b:.0f}, {avg_c:.0f})"
                  f"  Normalized: ({nr}, {ng}, {nb}, {nc})")

    # Calibrate "None" (empty slot) per sensor as a color
    input("\nRemove all ligands (empty slots) and press Enter...")

    empty_proxs = {}
    for ch in range(NUM_SENSORS):
        print(f"  Reading empty sensor {ch}...", end="", flush=True)
        avg = read_sensor_avg(service, ch)
        prox = read_proximity_avg(service, ch)
        if avg is None:
            print(" ERROR: no readings.")
            continue

        avg_r, avg_g, avg_b, avg_c = avg
        nr, ng, nb = service.normalize_rgb(avg_r, avg_g, avg_b)
        nc = service.normalize_clear(avg_r, avg_g, avg_b, avg_c)
        sensor_maps[ch]["None"] = {"r": nr, "g": ng, "b": nb, "nc": nc}

        if prox is not None:
            empty_proxs[ch] = prox

        print(f" done. Normalized: ({nr}, {ng}, {nb}, {nc})  Prox: {prox}")

    # Calibrate proximity thresholds
    input("\nPlace any ligand under ALL sensors and press Enter...")
    print("\n  Reading filled slot proximity values...")
    proximity_thresholds = {}
    for ch in range(NUM_SENSORS):
        print(f"  Reading sensor {ch}...", end="", flush=True)
        prox = read_proximity_avg(service, ch)
        if prox is not None and ch in empty_proxs:
            proximity_thresholds[ch] = round(
                (empty_proxs[ch] + prox) / 2
            )
            print(f" done. Prox: {prox:.1f}  "
                  f"(empty={empty_proxs[ch]:.0f}, threshold={proximity_thresholds[ch]})")
        else:
            print(f" done. Prox: {prox}")

    # Save
    color_map = {
        "_comment": "Per-sensor calibrated RGBC reference values. Generated by color_calibration.py.",
        "sensors": {str(ch): colors for ch, colors in sensor_maps.items()},
        "proximity_thresholds": {str(ch): t for ch, t in proximity_thresholds.items()},
    }

    with open(COLOR_MAP_PATH, "w") as f:
        json.dump(color_map, f, indent=2)

    print(f"\nCalibration saved to {COLOR_MAP_PATH}")
    print("\nCalibrated values per sensor:")
    for ch in range(NUM_SENSORS):
        print(f"\n  Sensor {ch}:")
        for name, vals in sensor_maps[ch].items():
            print(f"    {name}: R={vals['r']}, G={vals['g']}, B={vals['b']}, NC={vals['nc']}")


if __name__ == "__main__":
    calibrate()
